hmcts/lau-idam-backend

README.md
https://tools.hmcts.net/jira/browse/LAU-75
Update the configs
```
[ ] Yes
[x] No
```
=> LAU-75 Update configs

src/main/java/uk/gov/hmcts/reform/laubackend/idam/domain/IdamLogonAudit.java, src/main/resources/db/migration/V001__Schema.sql
https://tools.hmcts.net/jira/browse/LAU-76
Update to remove not null for ip_address column.
```
[ ] Yes
[x] No
```
=> LAU-76: Update to database nullable column.

src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/LogOnGetApiSteps.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/LogOnPostApiSteps.java
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> Fixing FN tests

build.gradle
https://tools.hmcts.net/jira/browse/LAU-226
LAU-226: Upgrade Log4j to 2.15.0
```
[ ] Yes
[x] No
```
=> LAU-226: Upgrade Log4j to 2.15.0

src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/LogOnApiTest.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/LogOnGetApiSteps.java
JIRA link (if applicable)
(https://tools.hmcts.net/jira/browse/LAU-225)
Change description
Automation FN tests Authorization/ServiceToken for Logons Api
```
[ ] Yes
[x] No
```
=>  Automation FN tests Authorization/ServiceToken for Logons Api

src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/model/LogOnGetResponseVO.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/response/LogonLogGetResponse.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/service/LogonLogService.java
https://tools.hmcts.net/jira/browse/LAU-208
Add totalNumberOfRecords
```
[ ] Yes
[x] No
```
=> LAU-208 Update BE to allow latest FE changes

audit.json
https://tools.hmcts.net/jira/browse/LAU-75
Add false positives to clear security scan issues.
```
[ ] Yes
[x] No
```
=> LAU-75: Suppress false positives

charts/lau-idam-backend/values.preview.template.yaml, src/integrationTest/resources/features/get_logon_audit.feature, src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditRepository.java, src/main/resources/db/migration/V002__Schema.sql
https://tools.hmcts.net/jira/browse/LAU-220
Fix case sensitivity in Case Audit/IdAM search page
```
[ ] Yes
[x] No
```
=> LAU-220 Fix case sensitivity in Case IdAM search page

src/main/java/uk/gov/hmcts/reform/laubackend/idam/controllers/IdamLogonAuditController.java
https://tools.hmcts.net/jira/browse/LAU-173
Document System Logons endpoints in Swagger
[ ] Yes
[x] No
=> LAU-173 fixed spelling and added 401 response code

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/LAU-181
Update sync branches
```
[ ] Yes
[x] No
```
=> LAU-181 Sync branches with master

build.gradle, src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/NotEmptyInputParamsVerifier.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/laubackend/idam/utils/NotEmptyInputParamsVerifierTest.java
https://tools.hmcts.net/jira/browse/LAU-172
A few small changes following local integration testing with IdAM-API.
1. ipAddress mandatory input param check removed.
2. Authorised service is from 'idam_api'.
```
[ ] Yes
[x] No
```
=> LAU-172: Update after testing with IdAM-API.

.github/workflows/swagger.yml, src/main/java/uk/gov/hmcts/reform/laubackend/idam/config/SwaggerConfiguration.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/config/SwaggerGeneratorTest.java
https://tools.hmcts.net/jira/browse/LAU-238
LAU IdAM - Automation of Swagger Documentation Publishing
[ ] Yes
[X] No
=> LAU-238 swagger generator test and Github action

src/test/java/uk/gov/hmcts/reform/laubackend/idam/config/SwaggerGeneratorTest.java
Update SwaggerGeneratorTest to fix jenkins master build.
```
[ ] Yes
[X] No
```
=> Update SwaggerGeneratorTest to fix jenkins master build.

src/integrationTest/resources/features/get_logon_audit.feature, src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditRepository.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/service/LogonLogService.java, src/main/resources/db/migration/V003__Schema.sql
Optimise lau-idam query.
Optimise lau-idam query.
```
[ ] Yes
[X] No
```
=> Optimise lau-idam query.

charts/lau-idam-backend/values.preview.template.yaml, src/main/resources/db/migration/V004__Schema.sql
https://tools.hmcts.net/jira/browse/LAU-258
Optimise lau-idam backend.
```
[ ] Yes
[X] No
```
=> LAU-258 Optimise lau-idam backend.

Jenkinsfile_CNP
Disable DB migration
```
[ ] Yes
[x] No
```
=> Disable DB migration.

Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml, src/main/resources/db/migration/V005__Schema.sql
Enabble DB migration
```
[ ] Yes
[x] No
```
=> Enable DB migration.

Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml, src/main/resources/db/migration/V005__Schema.sql
This reverts commit 3358c7bc53f207d624fe3e0bf34d6c180b386387.
This reverts commit 3358c7bc53f207d624fe3e0bf34d6c180b386387.
```
[ ] Yes
[x] No
```
=> Revert "Enable DB migration. (#96)"

src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditInsertRepository.java
https://tools.hmcts.net/jira/browse/LAU-282
Case parameters as strings required in insert sql.
```
[ ] Yes
[x] No
```
=> LAU-282: Update to case values in insert sql.

build.gradle
Fix dependency check and security scan Jenkins failures.
Fix dependency check and security scan Jenkins failures.
```
[ ] Yes
[x] No
```
=> Fix security scan and dependency check.

src/main/java/uk/gov/hmcts/reform/laubackend/idam/service/LogonLogService.java
https://tools.hmcts.net/jira/browse/LAU-217
When empty size/page passed through the request results in 500
```
[ ] Yes
[x] No
```
=> LAO-217 When empty size/page passed through the request results in 500

charts/lau-idam-backend/Chart.yaml
Upgrade java charts version
```
[ ] Yes
[x] No
```
=> Upgrade java charts version

Jenkinsfile_CNP, build.gradle, charts/lau-idam-backend/Chart.yaml, charts/lau-idam-backend/values.yaml, src/main/resources/bootstrap.yaml, src/main/resources/db/migration/V005__Schema.sql
https://tools.hmcts.net/jira/browse/LAU-320
Pass application db user password to flyway scripts
```
[ ] Yes
[x] No
```
=> LAU-320 Pass application db user password to flyway scripts

charts/lau-idam-backend/Chart.yaml
https://tools.hmcts.net/jira/browse/LAU-311
Update chart version
```
[ ] Yes
[x] No
```
=> LAU-311: Update chart version

src/test/java/uk/gov/hmcts/reform/laubackend/idam/utils/NotEmptyInputParamsVerifierTest.java
Update caseRef generator not generate caseRefs with leading zero
Update caseRef generator not generate caseRefs with leading zero
```
[ ] Yes
[X] No
```
=> Update caseRef generator not generate caseRefs with leading zero

src/main/java/uk/gov/hmcts/reform/laubackend/idam/constants/ExceptionMessageConstants.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/InputParamsVerifierHelper.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/utils/InputParamsVerifierTest.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/utils/LogonInputParamsVerifierGetExceptionTest.java
https://tools.hmcts.net/jira/browse/LAU-323
Improve LAU exception messages
```
[ ] Yes
[x] No
```
=> LAU-323 Improve LAU exception messages

build.gradle
https://tools.hmcts.net/jira/browse/LAU-366
Fix for Dependency check: postgresql , CVE-2022-21724
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> LAU-366: Dependency check postgresql

build.gradle
https://tools.hmcts.net/jira/browse/LAU-366
Fix vulnerability
```
[ ] Yes
[x] No
```
=> LAU-366: Fix vulnerability.

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-373
Update to suppress spring-plugin vulnerabilities.
```
[ ] Yes
[x] No
```
=> LAU-373: Suppress vulnerability with spring-plugin.

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-377
Suppress vulnerabilities.
```
[ ] Yes
[x] No
```
=> LAU-377: Suppress springfox vulnerabilities

security.sh
https://tools.hmcts.net/jira/browse/LAU-387
Fix security scan failures.
```
[ ] Yes
[x] No
```
=> LAU-387: Update to fix security scan.

build.gradle
https://tools.hmcts.net/jira/browse/LAU-367
This change is to upgrade Flywaydb and Flyway-core version from 8.2.2 to 8.5..5
```
[ ] Yes
[x] No
```
=> LAU-367 Bump flyway version

build.gradle
https://tools.hmcts.net/jira/browse/LAU-367
This change is to upgrade log4j version
```
[ ] Yes
[x] No
```
=> LAU-367 Log4j upgrade

build.gradle
https://tools.hmcts.net/jira/browse/LAU-367
This change is to upgrade com.gorylenko.gradle-git-properties, testng, bcpkix-jdk15on
```
[ ] Yes
[x] No
```
=> LAU-367 other upgrade

build.gradle
https://tools.hmcts.net/jira/browse/LAU-367
This change is to upgrade versions of some software
```
[ ] Yes
[x] No
```
=> LAU-367 More upgrades

build.gradle
Reverts hmcts/lau-idam-backend#29
=> Revert "Bump versions.junit from 5.7.2 to 5.8.2"

build.gradle
https://tools.hmcts.net/jira/browse/LAU-407
This change is to fix dependency check related to CVE-2022-29885
```
[ ] Yes
[x] No
```
=> PCQ-407 Dependency check fix

build.gradle, gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/LAU-410
This change is to review Dependabot PR and upgrade libraries
```
[ ] Yes
[x] No
```
=> LAU-410 Gradle and databind upgrade

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-413
This change is to fix Dependency check related to spring-security
```
[ ] Yes
[x] No
```
=> LAU-413 Dependency check fix

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-457
This change is to fix dependency check
```
[ ] Yes
[x] No
```
=> LAU-457 dependency check fixed

build.gradle
https://tools.hmcts.net/jira/browse/LAU-443
This change is to upgrade libraries
```
[ ] Yes
[x] No
```
=> PCQ-443 Upgrading libraries

build.gradle
https://tools.hmcts.net/jira/browse/LAU-443
This change is to upgrade libraries
```
[ ] Yes
[x] No
```
=> LAU-443More libraries upgarde

build.gradle
https://tools.hmcts.net/jira/browse/LAU-443
Some more Libraries have been upgraded
```
[ ] Yes
[x] No
```
=> LAU-443 upgrade libraries

src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/LAU-482
This change is to remove config properties
```
[ ] Yes
[x] No
```
=> Lau-482 removing config properties

src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/LAU-481
This change is to remove config properties
```
[ ] Yes
[x] No
```
=> Lau-481 Fortify scan fix

build.gradle
https://tools.hmcts.net/jira/browse/LAU-490
Upgrade postgres library to 42.4.1.
```
[ ] Yes
[x] No
```
=> LAU-490: Upgrade postgres library.

build.gradle
https://tools.hmcts.net/jira/browse/LAU-488
This change is to remove unneccessary libraries. 
```
[ ] Yes
[x] No
```
=> Remove Libraries

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-512
Remove suppression for log4j
```
[ ] Yes
[x] No
```
=> LAU-512 remove suppression for log4j

build.gradle
https://tools.hmcts.net/jira/browse/LAU-520
This change is to fix dependency check related to sankeyml
```
[ ] Yes
[x] No
```
=> LAU-520 dependency check fix

audit.json, security.sh
https://tools.hmcts.net/jira/browse/LAU-518
This change is to setup separate docker for security scan ZAP
```
[ ] Yes
[x] No
```
=> LAU-518 Seperate docker for Security Scan

audit.json
https://tools.hmcts.net/jira/browse/LAU-539
Adding missing audit suppression.
```
[ ] Yes
[x] No
```
=> LAU-539: Add missing audit suppression

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/LAU-524
This change is to disable nightly build during weekend
```
[ ] Yes
[x] No
```
=> LAU-524 disabling nightly build during weekend

build.gradle
https://tools.hmcts.net/jira/browse/LAU-553
This change is to fix dependency check related to spring-security and tomcat-embed
```
[ ] Yes
[x] No
```
=> LAU-553 dependency check fix

README.md
https://tools.hmcts.net/jira/browse/LAU-546
Add SonarQube badges and Overview section
```
[ ] Yes
[x] No
```
=> LAU-546 Add SonarQube badges and Overview section

.github/PULL_REQUEST_TEMPLATE.md, Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/LAU-549
Cleanup helm release on success
```
[ ] Yes
[x] No
```
=> LAU-549 Cleanup helm release on success

build.gradle, charts/lau-idam-backend/Chart.yaml
https://tools.hmcts.net/jira/browse/LAU-556
This change is for upgrading libraries
```
[ ] Yes
[x] No
```
=> LAU-556 upgrading libraries

build.gradle
https://tools.hmcts.net/jira/browse/LAU-569
Update Postgresql lib.
```
[ ] Yes
[x] No
```
=> LAU-569: Update postgresql

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-570
This change is to suppress h2 database
```
[ ] Yes
[x] No
```
=> LAU-570 h2 database suppresion

.dependabot/config.yml, .github/dependabot.yml
https://tools.hmcts.net/jira/browse/LAU-572
This change is for Dependabot configuration 
```
[ ] Yes
[x] No
```
=> LAU-572 dependabot configuration change

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-575
This change is to suppress CVE
```
[ ] Yes
[x] No
```
=> LAU-575 Suppressing CVE

.github/workflows/ci.yml, .github/workflows/swagger.yml, Jenkinsfile_CNP, Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/LAU-555
Update github workflow action versions.
```
[ ] Yes
[x] No
```
=> LAU-555: Update to resolve workflow deprecated versions.

build.gradle, charts/lau-idam-backend/Chart.yaml
https://tools.hmcts.net/jira/browse/LAU-577
This change is to upgrade dependencies.
```
[ ] Yes
[x] No
```
=> LAU-577 dependency upgrade

Jenkinsfile_CNP, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-584
This change is to suppress CVE
```
[ ] Yes
[x] No
```
=> LAU-584 CVE suppression

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-586
This change is to suppress CVE
```
[ ] Yes
[x] No
```
=> LAU-586 suppressing CVE

build.gradle
https://tools.hmcts.net/jira/browse/LAU-587
This Change is to fix CVE-2022-45143
```
[ ] Yes
[x] No
```
=> LAU-587 dependency check fix

src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/model/LogonLog.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/LogOnGetApiSteps.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/LogOnPostApiSteps.java, src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/LogonAuditGetSteps.java, src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/LogonAuditPostSteps.java, src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/helper/LogonAuditGetHelper.java, src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/helper/LogonAuditPostHelper.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/constants/ExceptionMessageConstants.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/constants/LoginState.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/domain/IdamLogonAudit.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/dto/LogonLog.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditInsertRepository.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditRepository.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/response/LogonLogResponse.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/service/LogonLogService.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/InputParamsVerifier.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/InputParamsVerifierHelper.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/NotEmptyInputParamsVerifier.java, src/main/resources/db/migration/V006__Schema.sql, src/main/resources/h2/V001__Schema.sql, src/test/java/uk/gov/hmcts/reform/laubackend/idam/controllers/IdamLogonAuditControllerTest.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/service/LogonLogServiceTest.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/utils/InputParamsVerifierTest.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/utils/NotEmptyInputParamsVerifierTest.java
https://tools.hmcts.net/jira/browse/LAU-583
Add idam login state column
```
[ ] Yes
[x] No
```
=> LAU-583 Add idam login state

.github/dependabot.yml, build.gradle
https://tools.hmcts.net/jira/browse/LAU-611
This change is to configure dependabot 
```
[ ] Yes
[x] No
```
=> Lau-611 dependabot configuration

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-580
This change is to remove suppression
```
[ ] Yes
[x] No
```
=> LAU-580 remove suppression

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-618
This change is to fix CVE-2022-1471
```
[ ] Yes
[x] No
```
=> LAU-618 suppressing CVE-2022-1471

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditInsertRepository.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditRepository.java, src/main/resources/db/migration/V007__Schema.sql, src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonRepositoryStartEndTimeTest.java, src/test/resources/application.yaml
https://tools.hmcts.net/jira/browse/LAU-617
Query performance improvement and remove h2 db
```
[ ] Yes
[x ] No
```
=> Query performance improvement and remove h2 db

build.gradle
CVE-2023-20861 fix
```
[ ] Yes
[x] No
```
=> CVE-2023-20861 fix

src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/CommonSteps.java, src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/LogonAuditDeleteSteps.java, src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/LogonAuditGetSteps.java, src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/helper/RestConstants.java, src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/helper/RestHelper.java, src/integrationTest/resources/features/get_logon_audit.feature, src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditRepository.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/NotEmptyInputParamsVerifier.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/laubackend/idam/controllers/IdamLogonAuditControllerTest.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonRepositoryStartEndTimeTest.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/utils/NotEmptyInputParamsVerifierTest.java
https://tools.hmcts.net/jira/browse/LAU-622
These changes are to improve performance for lau-idam-backend query 
```
[ ] Yes
[x] No
```
=> LAU-622 lau-idam-backend performance improvement

build.gradle
https://tools.hmcts.net/jira/projects/LAU/issues/LAU-649
Update libraries to address vulnerabilities
```
[ ] Yes
[x] No
```
=> LAU-649 bump spring security version to address vulnerability

src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditFindLogonRepository.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditRepository.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/service/LogonLogService.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonRepositoryStartEndTimeTest.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/service/LogonLogServiceTest.java
https://tools.hmcts.net/jira/browse/LAU-637
Refactor Idam Logon Audit query
```
[ ] Yes
[x] No
```
=> Refactor find idam logon query

audit.json
https://tools.hmcts.net/jira/browse/LAU-654
This change is to fix security scan.
```
[ ] Yes
[x] No
```
=> LAU-654 Security Scan fixed

audit.json
https://tools.hmcts.net/jira/browse/LAU-654
Security scan fix
```
[ ] Yes
[x] No
```
=> LAU-654 Security scan fix

src/main/java/uk/gov/hmcts/reform/laubackend/idam/domain/UserDeletionAudit.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/dto/UserDeletionUser.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditFindRepository.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditInsertRepository.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditRepository.java, src/main/resources/db/migration/V008__Schema.sql, src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionRepositoryStartEndTimeTest.java
https://tools.hmcts.net/jira/browse/LAU-634
Added user_deletion_audit table and model
```
[ ] Yes
[x] No
```
=> LAU-634 added user deletion audit model

src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/model/DeletedAccount.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/model/DeletedAccountsRequest.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/DeletedAccountsApiTest.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/LogOnApiTest.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/BaseSteps.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/DeletedAccountsPostApiSteps.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/LogOnGetApiSteps.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/LogOnPostApiSteps.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/utils/TestConstants.java, src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/UserDeletionAuditPostSteps.java, src/integrationTest/resources/features/post_user_deletion_audit.feature, src/main/java/uk/gov/hmcts/reform/laubackend/idam/constants/ExceptionMessageConstants.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/controllers/UserDeletionAuditController.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/domain/UserDeletionAudit.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/dto/DeletionLog.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/dto/UserDeletionUser.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/insights/AppInsightsEvent.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditFindRepository.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/request/UserDeletionPostRequest.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/response/UserDeletionPostResponse.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/service/UserDeletionAuditService.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/InputParamsVerifier.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/InputParamsVerifierHelper.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/NotEmptyInputParamsVerifier.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/controllers/UserDeletionAuditControllerTest.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/service/UserDeletionAuditServiceTest.java
https://tools.hmcts.net/jira/browse/LAU-640
Added POST endpoint to submit deleted accounts for auditing purposes
```
[ ] Yes
[x] No
```
=> LAU-640 user deletion audit log post request endpoint

audit.json
https://tools.hmcts.net/jira/browse/LAU-668
Fix merge conflict
```
[ ] Yes
[x] No
```
=> Update audit.json for merge conflict

audit.json, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/LAU-673
This change is for suppressing CVE-2023-20883
```
[ ] Yes
[x] No
```
=> Lau-673 suppress CVE

src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/helper/AuthorizationHeaderHelper.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/helper/DatabaseCleaner.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/DeletedAccountsApiTest.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/LogOnApiTest.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/BaseSteps.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/utils/TestConstants.java, src/integrationTest/resources/application.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/LAU-671
Added idam-user-disposer service to authorised services list
```
[ ] Yes
[x] No
```
=> LAU-671 add idam-user-disposer service to authorised services

build.gradle, src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/IdamLogonAuditInsertRepository.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditInsertRepository.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/security/SecurityConfiguration.java, src/main/resources/application.properties
https://tools.hmcts.net/jira/projects/LAU/issues/LAU-661
Bump Spring Boot 3.0.8 to 3.1.1
```
[ ] Yes
[x] No
```
=> LAU-661 bump Spring Boot 3.0.8 to 3.1.1

build.gradle
https://tools.hmcts.net/jira/browse/LAU-688
Bump tomcat dependency
```
[ ] Yes
[x] No
```
=> LAU-688 bump tomcat to address CVE-2023-34981

Jenkinsfile_CNP, build.gradle, src/contractTest/java/uk/gov/hmcts/reform/laubackend/idam/pacttests/IdamApiConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/laubackend/idam/pacttests/IdamConsumerTestBase.java, src/contractTest/resources/config/application_contract.properties
**Before creating a pull request make sure that:**
This is just a dry run to see if the pipeline publishes a pact to broker.
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> Pact testing

audit.json
https://tools.hmcts.net/jira/browse/LAU-719
Fix security scan
```
[ ] Yes
[x] No
```
=> LAU-719 security scan fix

audit.json
https://tools.hmcts.net/jira/projects/LAU/issues/LAU-723
Ignore ZAProxy warnings
```
[ ] Yes
[x] No
```
=> LAU-723 ignore zaproxy warnings

audit.json
https://tools.hmcts.net/jira/browse/LAU-723
Ignore zaproxy warnings
```
[ ] Yes
[x] No
```
=> LAU-723 ignore other zaproxy warnings

build.gradle
https://tools.hmcts.net/jira/browse/LAU-730
Bump tomcat to address CVE-2023-41080
```
[ ] Yes
[x] No
```
=> Lau 730 bump tomcat CVE 2023 41080

src/main/java/uk/gov/hmcts/reform/laubackend/idam/response/UserDeletionGetResponse.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/service/UserDeletionAuditService.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/service/UserDeletionAuditServiceTest.java
https://tools.hmcts.net/jira/browse/LAU-734
Added total deleted users count property
```
[ ] Yes
[x] No
```
=> LAU-734 add total deleted users count property

Jenkinsfile_CNP
Do not sync demo branch with master for flexible postgres migration
```
[ ] Yes
[x] No
```
=> LAU-733 do not sync demo branch with master

Jenkinsfile_CNP
Sync master with demo
Sync master with demo
```
[ ] Yes
[x] No
```
=> Sync master with demo

infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/LAU-803
Increase flexible server size in prod
```
[ ] Yes
[x] No
```
=> LAU-803 increase size for postgres flexible server

infrastructure/main.tf, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/DeletedAccountsApiTest.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/LogOnApiTest.java
Add read user for postgres flexible 
Add read user for postgres flexible 
```
[ ] Yes
[x] No
```
=> Add read user for postgres flexible [*** MERGE ONLY AFTER FLEXIBLE SERVER MIGRATION TONIGHT ***]

src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/DeletedAccountsApiTest.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/LogOnApiTest.java
The functional tests were disabled to allow the pipeline to pass for flexible server migration
```
[ ] Yes
[x] No
```
=> Enable functional tests

src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/AllDeletedAccountsApiTest.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/runner/DeletedAccountsApiTest.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/steps/DeletedAccountsGetApiSteps.java, src/functionalTest/java/uk/gov/hmcts/reform/laubackend/idam/serenityfunctionaltests/utils/TestConstants.java, src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/UserDeletionAuditGetSteps.java, src/integrationTest/resources/features/get_user_deletion_audit.feature, src/main/java/uk/gov/hmcts/reform/laubackend/idam/constants/ExceptionMessageConstants.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/controllers/UserDeletionAuditController.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/dto/DeletionLogAllUsersRequestParams.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/insights/AppInsightsEvent.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditFindRepository.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/service/UserDeletionAuditService.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/InputParamsVerifier.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/utils/InputParamsVerifierHelper.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/laubackend/idam/controllers/UserDeletionAuditControllerGetAllTest.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/service/UserDeletionAuditServiceTest.java
https://tools.hmcts.net/jira/browse/LAU-817
This change is regarding getAllDeletedAccounts end point
```
[ ] Yes
[x] No
```
=> LAU-817 Get all Deleted User end point

build.gradle
https://tools.hmcts.net/jira/browse/LAU-822
Bump spring boot to 3.1.6
```
[ ] Yes
[x] No
```
=> LAU-822 bump spring to 3.1.6

build.gradle, infrastructure/main.tf
Jenkins flyway migration step is using hardcoded secret variable names and therefore migration is happening on old database server. Update these hardcoded secrets values to point to new server
```
[ ] Yes
[x] No
```
=> LAU-769 update hardcoded variables to use new values

charts/lau-idam-backend/Chart.yaml, charts/lau-idam-backend/values.yaml
Update values.yaml to point to flexible server
```
[ ] Yes
[x] No
```
=> LAU-769 update values.yaml with flexible server

infrastructure/main.tf, infrastructure/variables.tf
Update app db username in keyvault
```
[ ] Yes
[x] No
```
=> LAU-769 update app-db-user to lauuser

charts/lau-idam-backend/Chart.yaml, charts/lau-idam-backend/values.yaml
Use the new key for db app user in the app.
```
[ ] Yes
[x] No
```
=> Lau 769 update idam db user tf

src/main/resources/application.yaml
Temporarily use lauadmin for db connection
```
[ ] Yes
[x] No
```
=> LAU-769 temporarily use lauadmin use for db connection

src/main/resources/application.yaml
Reverting back to use lauuser after platops confirmed they are able to connect to prod DB using lauuser
```
[ ] Yes
[x] No
```
=> LAU-769 revert back to using lauuser for db connection

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/LAU-777
Removing references to single server from terraform
```
[ ] Yes
[x] No
```
=> LAU-777 remove single server terraform

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/LAU-777
Do not wait for resource group to be empty before dropping resource group
```
[ ] Yes
[x] No
```
=> Lau 777 remove single server terraform

build.gradle
Bump pitest junit plugin version to 1.2.1
```
[ ] Yes
[x] No
```
=> bump pitest junit plugin version to 1.2.1

infrastructure/main.tf
Remove setting from terraform that doesn't wait for resource groups to be empty before removing
```
[ ] Yes
[x] No
```
=> Remove prevent deletion if contains resource setting

build.gradle
Removed some old overwrites, resolved google-collections dependency
```
[ ] Yes
[x] No
```
=> Clean dependencies a bit

charts/lau-idam-backend/Chart.yaml, charts/lau-idam-backend/values.yaml
https://tools.hmcts.net/jira/browse/LAU-842
Enable spotInstances
=> LAU-842 enable spot instances

lib/applicationinsights.json
[LAU-847](https://tools.hmcts.net/jira/browse/LAU-847)
Disable dependency logs
=> LAU-847 disable dependency tracking

infrastructure/main.tf
[LAU-850](https://tools.hmcts.net/jira/browse/LAU-850)
Enable auto grow size on postgres
=> LAU-850 enable postgres auto grow

src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditFindRepository.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditInsertRepository.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionAuditRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/repository/UserDeletionRepositoryStartEndTimeTest.java
[LAU-873](https://tools.hmcts.net/jira/browse/LAU-873)
Make search case and whitespace around insensitive
=> LAU-873 normalise search and insertion to trim and make lowercase

src/main/resources/db/migration/V011__Schema.sql
https://tools.hmcts.net/jira/browse/LAU-856
* Rename existing user deletion table to preserve it.
* Create a new table with the same name.
=> LAU-856 rename existing db table and create and empty one

build.gradle, config/owasp/suppressions.xml
Bumped jackson-databind, removed CVE suppression
=> Bump jackson-databind

charts/lau-idam-backend/Chart.yaml
Bump java chart version to OCI version
```
[ ] Yes
[x] No
```
=> Bump java chart to oci compliant

infrastructure/main.tf
remove plpgsql azure extension
```
[ ] Yes
[x] No
```
=> Update main.tf to remove plpgsql azure extension

infrastructure/prod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CME-130
Leave db monitoring only on prod.
```
[ ] Yes
[x] No
```
=> CME-130 leave db monitoring only on prod

build.gradle
https://tools.hmcts.net/jira/browse/CME-515
Replace jitpack with azure artifactory
```
[ ] Yes
[x] No
```
=> CME-515 replace jitpack with azure

src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/AbstractSteps.java, src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/CommonSteps.java, src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/LogonAuditGetSteps.java, src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/LogonAuditPostSteps.java, src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/helper/RestConstants.java, src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/helper/RestHelper.java, src/integrationTest/resources/features/get_logon_audit.feature, src/integrationTest/resources/features/post_logon_audit.feature, src/main/java/uk/gov/hmcts/reform/laubackend/idam/authorization/HttpPostRecordHolder.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/authorization/ServiceAuthorizationAuthenticator.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/feign/FeignErrorDecoder.java, src/main/java/uk/gov/hmcts/reform/laubackend/idam/feign/RetryableFeignConfig.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/laubackend/idam/feign/FeignErrorDecoderTest.java, src/test/java/uk/gov/hmcts/reform/laubackend/idam/feign/RetryableFeignConfigTest.java
https://tools.hmcts.net/jira/browse/LAU-1138
Trying lau-idam-backend with retry only
```
[ ] Yes
[x] No
```
=> LAU-1138 with retry only 

src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/AbstractSteps.java, src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/bdd/LogonAuditPostSteps.java, src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/helper/RestConstants.java, src/integrationTest/java/uk/gov/hmcts/reform/laubackend/idam/helper/RestHelper.java, src/integrationTest/resources/features/post_logon_audit.feature, src/main/java/uk/gov/hmcts/reform/laubackend/idam/authorization/ServiceAuthorizationAuthenticator.java
https://tools.hmcts.net/jira/browse/LAU-1138
One more integration test without retry
```
[ ] Yes
[x] No
```
=> Lau 1138 no retry for 401
